on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions: read-all

jobs:
  test:
    runs-on: windows-2019

    env:
      workdir: '${{ github.workspace }}'

    timeout-minutes: 60

    defaults:
      run:
        shell: cmd /C CALL {0}

    steps:
      - uses: actions/checkout@v4.1.7

      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          conda-build-version: '*'
          channels: conda-forge,nodefaults
          activate-environment: test_env
          python-version: "3.12"

      - name: Create conda channel with the artifact bit
        shell: cmd /C CALL {0}
        run: |
          echo ${{ env.workdir }}
          mkdir ${{ env.workdir }}\channel
          mkdir ${{ env.workdir }}\channel\win-64
          copy artifacts\dpctl-*.tar.bz2 ${{ env.workdir }}\channel\win-64
          dir ${{ env.workdir }}\channel\win-64

      - name: Remove defaults channel
        run: conda config --remove channels defaults

      - name: Index the channel
        shell: cmd /C CALL {0}
        run: conda index ${{ env.workdir }}\channel

      - name: List content of the channels
        shell: cmd /C CALL {0}
        run: |
          dir ${{ env.workdir }}\channel
          dir ${{ env.workdir }}\channel\win-64

      - name: Dump dpctl version info from created channel into ver.json
        shell: cmd /C CALL {0}
        run: |
          @echo on
          conda search dpctl -c ${{ env.workdir }}/channel --override-channels --info --json > ${{ env.workdir }}\ver.json
          dir ${{ env.workdir }}

      - name: Output content of produced ver.json
        shell: pwsh
        run: Get-Content -Path ${{ env.workdir }}\ver.json
